apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: roundcube
spec:
  secretName: roundcube
  commonName: roundcube.kubernetes-cluster.ru
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
