apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: bar
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: bar.kubernetes-cluster.ru
    http:
      paths:
      - path: /
        backend:
          serviceName: bar
          servicePort: 80
