apiVersion: v1
kind: Pod
metadata:
  name: baz
spec:
  containers:
    - name: baz
      image: alpine
      command: ["/bin/sh"]
      args: ["-c", "trap 'exit 0' 15;while true; do exec sleep 100 & wait $!; done"]
      volumeMounts:
        - mountPath: "/pvc"
          name: baz
  volumes:
    - name: baz
      persistentVolumeClaim:
        claimName: baz
